services:
  - type: web
    name: backend
    rootDirectory: backend  # Set backend as the working directory
    env: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: DB_URL
        sync: false
      - key: PORT
        value: "5000"
