services:
  - type: web
    name: backend
    env: node
    buildCommand: cd backend && npm install
    startCommand: cd backend && npm start
    envVars:
      - key: DB_URL   # Match this with your .env file
        sync: false
      - key: PORT
        value: "5000"

