services:
  - type: web
    name: backend
    rootDirectory: backend  # Important: Tell Render to look inside the backend folder
    env: node
    buildCommand: npm install
    startCommand: node index.js
    envVars:
      - key: DB_URL
        sync: false
      - key: PORT
        value: "5000"
